### ISSUE TITLE
OSC: device can send to modules, but no feedback

### ISSUE THREAD

**Issue by DomiKamu** [j4s0n-c/trowaSoft-VCV#14]
Configs:
- friend: Windows 10 Pro x64 (French), Android Galaxy Tab.
- mine: Windows 7 Pro SP1 x64 (French), iPad 3 (iOS v9.3).
Both: same IP network, firewall is disabled (to be sure).

Hi,

Together with a French friend, we've tried the TouchOSC layout (downloaded from your main website), friend uses an Android device, I'm using an iPad 3, but in both cases, we can control trigSeq, trigSeq64 and voltSeq, but we don't have any feedback coming from module to our respectives devices.

Is it normal, or not?

In case you'd like we'll do more tests, don't hesitate!

Thanks a lot in advance.

Dominique.

**Comment by chichian** [comment]
Hi Dominique,

Hmm. That's not normal. There should be feedback coming from the sequencers to your device.  Here's what I can think of off the top of my head, although you may have already checked these:

1. [RACK] In the OSC setup on the sequencer, double check the **IP Address** field is set to the IP of your Galaxy Tab or iPad.
2. [RACK] In the OSC setup on the sequencer, double check the **Out Port** is set to the "Port (incoming)" in TouchOSC.
3. [RACK] In the OSC setup on the sequencer, double check that "**touchOSC**" is selected from the client dropdown list (instead of "Generic").

If you've already checked that, we can wait for j4s0n's feedback since he's actually more adept at TouchOSC than I am.

**Comment by DomiKamu** [comment]
Hi (again),

Okay we must have feedback, so assuming "something is wrong somewhere".

Of course all of them have been checked many times.
Friend I've mentioned uses same in/out ports (9000 and 9001) along an Arduino device and works fine.

I'm familiar about Lemur (iOS version) and PC, via both MIDI or/and OSC.

So we'll must investigate more deeply.

Thanks for your quick reply, really appreciated!

Dominique. (I close this issue BTW)
