### ISSUE TITLE
FEATURE REQUEST - voltSeq: another default voltages/notes

### ISSUE THREAD

**Issue by DomiKamu** [j4s0n-c/trowaSoft-VCV#15]
Hi again, for feature request.

For future releases, about **voltSeq**, is it possible, for any step, to change default to **0V** (instead of -10.0V) and default notes pitched to **C5** (instead of C0), assuming 0V / C5 is "middle position" (delivered voltages by the seq are bipolar -10V/+10V, I presume following "1V/octave" rule). Also I've understood voltages and notes (across modes) are linked.

Thanks (again) in advance if you'll can consider this request, for future releases of trowaSoft seqs.

Dominique.

**Comment by chichian** [comment]
Hi Dominique, 

Sure. This is something we were thinking of changing too. We had chosen the lowest value for the "default" initially so that "Pattern" mode would default to Pattern Num 1, but it is inconvenient for the other modes. I will see if I can change the default value whenever you change the mode (so it's always a value that makes sense for that mode).

FYI: The latest version voltSeq should now use C4 = 0V (another [user pointed out](https://github.com/j4s0n-c/trowaSoft-VCV/issues/9) that Rack recommends C4 to be 0V).

Thanks for the suggestion!

**Comment by DomiKamu** [comment]
Excellent! I've seen C4 <=> 0V from VCV Voltage Standards, if I'm remember. ;)

**Comment by chichian** [comment]
Hi Dominique,

This was changed in the new [0.6 release](https://github.com/j4s0n-c/trowaSoft-VCV/releases/tag/v0.6.0).  Thanks!

**Comment by DomiKamu** [comment]
Hi Jason, I've seen it, thanks! I close this issue.
