### ISSUE TITLE
cvOSCcv - Output conversion not functioning correctly.

### ISSUE THREAD

**Issue by dataphreak1001** [j4s0n-c/trowaSoft-VCV#41]
![image](https://user-images.githubusercontent.com/11288314/62837608-2fe7a480-bc26-11e9-8e9f-55f3f6d0ab96.png)

I'm trying to convert random cv to a 1 or 0 integer value, but the receiving software is getting a variety of responses. CV is produced by caudal, and ranges from -5.0 to +5.0. I've set it to 0 and 1 here because a want the mid point to favor slightly into the + spectrum because of the nature of the caudal model. Does cvOSCcv not truncate values that exceed the input values? This could just as easily be user error.

You'll need to zoom in, but you can see that channel 6 is transmitting an integer value of 2 to TD.

**Comment by chichian** [comment]
Hi dataphreak1001,

Currently, it only remaps the voltage input range (**Control Voltage (IN)**) to the new range (**OSC Value (OUT)**), so it **doesn't clip/truncate/filter** the input voltages like that. It just uses those limits to [rescale](https://github.com/VCVRack/Rack/blob/dca30e2b53ffff0e34343b8a67fd57d5dd63dc2a/include/math.hpp#L141) the outgoing value, then truncates/forces that rescaled value to an integer.

### (1) If you want to rescale:
Generally, you would set your **Control Voltage (IN)** MIN and MAX to what you are actually feeding it (the -5 and +5 V), but since you only want to produce a 0 or 1 OSC output, this would hardly ever produce a 1 (since 0.99 would truncate to 0 still).  I would try to set them to -10 and 10 V, and the **OSC Value (OUT)** values to 0 and 2. This way you will never actually get a "2" (because that would be have to an input voltage of +10V), and you would get your 0s and 1s. 

If you want more 1s than 0s in the OSC output, then set the **Control Voltage (IN)** to something like -12 V and +8 V to shift the output more towards 1s. (Or maybe do the opposite if I reversed that in my head).

### (2) If you want to truncate/clip the input:
Currently not supported, but I am working on cvOSCcv upgrades right now so if j4s0n is cool with it, we could add that in.

Sorry that the conversions are confusing.  Let us know if you (1) was what you wanted and if it worked or if you were looking for (2).

**Comment by dataphreak1001** [comment]
Not confusing at all. Super clear. Behavior may be intended, too. I can always throw an attenuverter in the path to bend the voltages to what I need. That's how I've been dealing with it lately. Easier to do in VCV Rack than Touch Designer, anyway. And if J4s0n feels like the way it's acting currently is intended behavior I totally understand. It was just giving weird outputs when I exceeded the CV In threshold. Still getting the job done: https://www.twitch.tv/videos/465802467?t=00h36m01s
