### ISSUE TITLE
V2 Prerelease (voltSeq) infers with rendering modules in display browser 

### ISSUE THREAD

**Issue by Stubs42** [j4s0n-c/trowaSoft-VCV#59]
Hi,
 When I am using a few voltseqs in a patch I recognized that the modules in the module browser didn't render anymore.
 Tracked that down to be the voltseqs causing this problem. If I delete all of them, modules are rendered quick and normal in the module browser. Adding one voltseq slows down rendering of modules in the module browser significantly. Use even more instances of voltSeq makes the browser not to render any modules at all (only cached ones are displayed). This is strange but reproducible.
Don't know how modules in the patch could possibly have an impact of rendering the modules in the browser.
Seems that the widgets are drawn without module being set when displayed in module browser.
Maybe there is some problems with your widgets if module hasn't been initialized. Just a guess.
Regards
Dieter

**Comment by chichian** [comment]
Hi Dieter,

That is weird. I am not seeing that. I downloaded and compiled a bunch of modules (for Rack Dev version) to inflate my module list--I still only have like 200 something, but my list still renders fine on a fresh start of Rack and reloading my save (a little bit of delay as you scroll) with five (5) voltSeqs in the patch (plus two (2) multiSeqs, one (1) trigSeq64, some cvOSCcv's with expanders talking to each other and some other random modules).  I tested on Windows with my graphics card enabled (mobile GTX 1060) and with it disabled (weak Intel HD graphics) and the only difference was w/o my dedicated card enabled, it rendered a little slower both with and without voltSeqs in the patch (each time tested restarting Rack so that nothing was cached).

j4s0n just tested on his older Mac laptop (I think only GT6xx series graphics?) and in power saver mode (no dedicated graphics), the list always rendered a little delayed (he has over 1000 modules). After turning power saver off, it rendered a little delayed but faster. This was again with and without several voltSeqs in the patch.

I think having the widget render with no module was introduced a while back in v1 if memory serves? If there were problems from the widget having no module, I think it should crash from NULL reference or getting a garbage reference / bad memory access (like it did when I did the conversion to v1)... But I can try to look into it.

**How many modules are in your browser list? And what OS, CPU, and GPU do you have?**

And you're OK to compile from source right (since you make your own plugin)? I can push my latest changes too and maybe that will some how fix it. I think I went through and found all the spots where I was loading the font in widget constructors and now load the font faces in the render portion (and also changed the rendering of lit objects to go into renderLayer())... I thought this would only matter when running as VST though.
